#!/bin/bash

# Skripti algus

# Kontrollib kas skripti käivitaja on kasutaja "root"
if [ "$EUID" -ne 0 ]; then
    echo "This script must be run with root privileges. Please use 'sudo'."
    exit 1
fi

# Kontrollib kas MySQL on olemas
if dpkg -l | grep -q "mysql-server"; then
    echo "MySQL is already installed on this system."
else
    echo "Installing MySQL..."
    apt update
    apt install mysql-server -y

    # Kontrollib kas allalaadimine on õnnestunud
    if dpkg -l | grep -q "mysql-server"; then
        echo "MySQL has been successfully installed."
    else
        echo "Failed to install MySQL. Please check for errors."
    fi
fi

# Skripti l6pp
