#!/bin/bash

# Skripti algus

# Kontrollib kas skripti käivitab "root" kasutaja
if [ "$EUID" -ne 0 ]; then
    echo "This script must be run with root privileges. Please use 'sudo'."
    exit 1
fi

# Kontrollib kas Apache on juba installitud
if dpkg -l | grep -q "apache2"; then
    echo "Apache is already installed on this system."
else
    echo "Installing Apache..."
    apt update
    apt install apache2 -y

    # Kontrollib kas Apache alla laadimine on õnnestunud
    if dpkg -l | grep -q "apache2"; then
        echo "Apache has been successfully installed."
    else
        echo "Apache installation failed. Please check for errors."
    fi
fi

# Skripti l6pp
